define TOKEN_URL_PREFIX to route emulator token requests, make it pretty
gladly-team/next-firebase-auth pull request #108
Opened 2021-03-13 19:22 UTC by litewarp

Add Feature from #63 #59 

When using the Auth Emulator, all requests for google tokens should be router to the emulator address and not the actual google endpoint, otherwise the tokens won't match.

The change now checks if the FIREBASE_AUTH_EMULATOR_HOST environment variable is provided, and if so, prefixes the request with the unsecured host rather than the secured https call to google.

2021-03-18 23:23 UTC, kmjennison requested changes
Please add full test coverage for this. Let me know if you need any help thinking through those tests.

We'll also want to document how to use the emulator, though that's fine to do in a future PR.

2021-03-20 04:00 UTC, litewarp commented
Thanks for the feedback. I’ll dive in this weekend. One big question I have though is whether you want to let users opt-in to using the emulator through the package or not — i.e. the user could input the local host address in the config and on init, the package initializes the auth instance with the emulator rather than having the user do it beforehand. 

Pros - easier to test against. If user didn’t set option but env variables exist we could warn or throw. Could also prevent race conditions on initialization with other parts of firebase but I haven’t had many issues with that. 

Cons are yet another config option and it’s probably better that the package is agnostic to the environment. 

Thoughts?

2021-03-20 18:00 UTC, kmjennison commented
Great question. I prefer we use the config: it doesn't prescribe a specific env var that the developer has to use (e.g., avoids conflicts) and keeps everything in one place. The developer can still use an env var to set the config if they'd like.

How about `firebaseAuthEmulatorHost` at the top level of the config?

We'll also want to update the typescript definition for the config, too.

2021-04-03 20:02 UTC, kmjennison requested changes
This looks great! Thanks for the excellent tests. Just one request to tweak the Jest tests, then we should be good to merge. Let me know if you want to update the README, otherwise I'm happy to.

2021-04-05 00:54 UTC, litewarp commented on src/__tests__/config.test.js
> +  // since we are adding to process.env, take a clone and reset after each test to prevent a memory leak
Thanks! Hoisted the `afterEach` logic as you suggested.

2021-04-05 00:54 UTC, litewarp commented on src/__tests__/firebaseAdmin.test.js
> +    })
Done.

2021-04-05 19:27 UTC, kmjennison approved these changes
Looks great. Thanks, @litewarp!

2021-04-05 19:28 UTC, merged

2021-04-05 19:37 UTC, kmjennison commented
Released in [v0.13.0-alpha.1](https://github.com/gladly-team/next-firebase-auth/releases/tag/v0.13.0-alpha.1).