Add Feature: Dynamic redirects
gladly-team/next-firebase-auth pull request #121
Opened 2021-04-06 10:44 UTC by litewarp

Implementation of dynamic redirects in discussion at #57.

2021-04-06 20:59 UTC, kmjennison requested changes
This looks excellent. Thank you for yet another contribution and for the great tests!

Only recommending a few tiny changes, then happy to merge.

2021-04-06 20:59 UTC, kmjennison commented on src/__tests__/withAuthUser.test.js
> +    expect(propsSpy.ctx).not.toBeTruthy()
To be more precise, use `toBeUndefined()`.

2021-04-06 20:59 UTC, kmjennison commented on src/__tests__/withAuthUser.test.js
> +    expect(ctxSpy).not.toBeTruthy()
Use `toBeUndefined()`.

2021-04-06 20:59 UTC, kmjennison commented on src/__tests__/withAuthUserTokenSSR.test.js
> +  it('redirects to the provided function login URL when the user is not auth and auth *is* required', async () => {
Typo: "when the user is not **authed**"

2021-04-06 22:10 UTC, litewarp commented
> This looks excellent. Thank you for yet another contribution and for the great tests!

Thanks! Thank you for the great library.

2021-04-07 00:19 UTC, kmjennison approved these changes
LGTM! 🎊

2021-04-07 00:19 UTC, merged