add multi-tenancy compatibility
gladly-team/next-firebase-auth pull request #132
Opened 2021-04-09 08:12 UTC by Twister42

A small modification so we can use multi-tenancy with the lib

2021-04-09 21:48 UTC, kmjennison requested changes
Thanks! Please add tests to cover the tenant logic (see code coverage comments) or let me know if you run into any trouble.

2021-04-09 21:48 UTC, kmjennison commented on src/firebaseAdmin.js
> +    return admin.auth().tenantManager().authForTenant(AuthUser.tenantId)
Please add test coverage for this.

2021-04-09 21:48 UTC, kmjennison commented on src/initFirebaseClientSDK.js
> +      firebase.auth().tenantId = firebaseClientInitConfig.tenantId
Please add test coverage for this.

2021-06-03 21:02 UTC, closed without merging

2021-06-10 07:24 UTC, locona commented
@kmjennison 
Why did you close this one?

2021-06-10 08:08 UTC, Twister42 commented
Probably because I never made the unit tests...
I didn't find the time yet. I need to release my app first :)

2021-06-10 10:01 UTC, locona commented
@Twister42 

I understand!

May I create a test and submit my PR when you have time?

2021-06-10 10:13 UTC, Twister42 commented
Sure ! I didn't commit the tests because I didn't find a good way to do them (I'm quite noob in JS and TS)
But if you have time and is willing to make them you're most welcome I'll add them to the PR as fast as I can

2021-06-10 13:12 UTC, locona commented
OK! Thanks !

2021-06-10 16:35 UTC, kmjennison commented
Yes, I closed this because it had been inactive for a while and has merge conflicts, but I welcome an updated PR. Thank you both for contributing!