feat: allow child or loader render while redirecting to app
gladly-team/next-firebase-auth pull request #369
Opened 2021-12-14 08:48 UTC by abusada

Fixes https://github.com/gladly-team/next-firebase-auth/issues/364

2021-12-14 23:03 UTC, kmjennison requested changes
Thank you for the comprehensive PR! Some minor changes requested.

2021-12-14 23:03 UTC, kmjennison commented on src/__tests__/withAuthUser.test.js
>      expect(container.firstChild).toBeNull()
In the above test, change description to "renders null by default when redirecting to the app".

2021-12-14 23:03 UTC, kmjennison commented on src/__tests__/withAuthUser.test.js
>    it('renders null when redirecting to the app, even while waiting for authRequestCompleted', () => {
Also change to "renders null by default"

2021-12-14 23:03 UTC, kmjennison commented on src/__tests__/withAuthUser.test.js
> +
Please add a test for when `whenAuthedBeforeRedirect` is set to `AuthAction.SHOW_LOADER`.

2021-12-15 12:17 UTC, abusada commented
@kmjennison updated the PR according to your review

2021-12-17 16:24 UTC, kmjennison approved these changes
Looks great, thanks!

2021-12-17 16:25 UTC, merged