feat(firebaseAdmin): fix to pass user custom user claims to createCustomToken
gladly-team/next-firebase-auth pull request #495
Opened 2022-07-14 08:58 UTC by takashi

As refer to the discussion https://github.com/gladly-team/next-firebase-auth/issues/317, currently we can not retrieve custom user claims that sets on firebase user from the custom token that created in server side. 

So, I added the second argument for adding custom claims.

Please tell me if I send this PR by wrong manner for this repository 🙇 

Thanks for great library!

2022-07-15 09:33 UTC, kamami commented
Waiting for this :)

2022-07-21 00:12 UTC, kmjennison requested changes
This looks great, thanks! Please add unit tests to [`firebaseAdmin.test.js`](https://github.com/gladly-team/next-firebase-auth/blob/f42993567d499115dc0de0b3b581971d1bcfd0f9/src/__tests__/firebaseAdmin.test.js#L243).

2022-09-05 02:15 UTC, RustedBuckett commented
Any updates on this? Ran into this issue today.

2023-06-30 23:54 UTC, kmjennison commented
Closed in favor of #654.

2023-06-30 23:54 UTC, closed without merging