Handle fetch top-level errors and retry network errors
gladly-team/next-firebase-auth pull request #618
Opened 2023-02-28 22:26 UTC by valeriangalliat

*Diff best viewed in ignore whitespaces mode.*

## Handle fetch top-level errors

This PR wraps the `await fetch` calls to login and logout API endpoints by a `try/catch` block so that we call `onLoginRequestError` and `onLogoutRequestError` not-only in case of HTTP errors, but also in case of network errors (e.g. `fetch` [rejecting](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#checking_that_the_fetch_was_successful) with `TypeError: failed to fetch`), instead of leaving those unhandled.

## Retry network errors

Also in order to mitigate network errors, this PR introduces a retry logic when calling  the login and logout API endpoints, provided by [fetch-retry](https://www.npmjs.com/package/fetch-retry).

This module defaults to retrying up to 3 times at 1s intervals, and only retrying network errors (the case where `fetch` rejects, as opposed to HTTP errors where it resolves with `response.ok = false`).

I think those defaults are sensible, and I added a configuration option `fetchRetryConfig` to allow fine tuning the retry logic if needed.

---

I think the rate of fetch network errors I'm seeing on login API calls is exacerbated by the fact the login API is called on every page (https://github.com/gladly-team/next-firebase-auth/issues/424 - I tried coming up with a solution for that too but didn't find a reliable way to do that just yet), nevertheless this PR shouldn't leave those errors _unhandled_, and thanks to the retry logic, should lower their frequency.

Let me know what you think and if you need me to make any edits!

2023-03-01 16:28 UTC, kmjennison commented
@valeriangalliat Thanks for the PR!

The try/catch behavior makes sense and would be good to merge. Could you break that into its own PR?

I don't think we should add `fetch-retry` as a dependency, given that developers might prefer other fetch implementations and it'll add to bundle size. Instead, I see two alternatives:

1. Developers should define the global fetch to have desired behavior. There was [a Next.js issue to build in fetch retries](https://github.com/vercel/next.js/issues/16787), though I'm not sure what the outcome was. It's also not clear to me how easy it is to change the default fetch polyfill ([related issue](https://github.com/vercel/next.js/issues/10509)). If anybody has any suggestions on best practices for modifying global fetch, please chime in. 
2. This library could take a `fetcher` function as an input. E.g., how SWR does this: https://swr.vercel.app/docs/data-fetching#fetch

2023-03-01 16:29 UTC, kmjennison requested changes
Please break out the try/catch changes into its own PR, excluding the addition of fetch-retry.

2023-03-02 21:08 UTC, valeriangalliat commented
That makes sense! I like the idea of the `fetcher` function. I'll split the changes and make another PR for that early next week 👌

2023-03-08 22:08 UTC, valeriangalliat commented
@kmjennison updated! This PR now only includes catching of fetch errors

2023-03-09 20:20 UTC, kmjennison approved these changes
LGTM. Thank you!

2023-03-09 20:20 UTC, merged