Let user specify the firebase app name
gladly-team/next-firebase-auth pull request #716
Opened 2024-06-27 20:43 UTC by MvRemmerden

2024-06-28 17:48 UTC, MvRemmerden commented
@kmjennison I think this PR might be ready, would you mind approving it to be deployed on Vercel so we can see whether any of the checks fail? 🙂

2024-06-28 22:02 UTC, kmjennison requested changes
@MvRemmerden Thanks for this! The approach looks good. Could you investigate the failing tests?

2024-06-29 09:48 UTC, MvRemmerden commented
@kmjennison I might need some help here. It looks like the problem is due to this change here: https://github.com/gladly-team/next-firebase-auth/pull/716/files#diff-40051885c173eb84152e58b7e9f3cbac7bd1e5d9de2520a1bd2a4253b4a6b9a0R108

I'm not sure if we just need to adapt the test to ensure that the app is initialized before, or if there is a bug here in the actual code.

Would you mind having a look yourself?

2024-06-29 10:21 UTC, MvRemmerden commented
Update: I think I got it working, it might have just been missing mocked configs in the tests, everything is passing now ✅

2024-07-01 13:58 UTC, kmjennison requested changes
One change needed and otherwise looks good.

2024-07-01 13:58 UTC, kmjennison commented on src/configTypes.ts
> +  firebaseClientAppName: 'example-app-name',
```suggestion
```

We shouldn't set a default app name.

2024-07-01 14:22 UTC, MvRemmerden commented
@kmjennison Awesome, committed, back to you 🙂

2024-07-01 14:26 UTC, kmjennison approved these changes
LGTM! Thanks for your work on this!

2024-07-01 14:27 UTC, merged